libpng 1.6.34 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib 1.2.11 gcc@5.5.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7_noentry
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: zlib 1.2.11
      gcc@5.5.0 linux-centos7-x86_64, HASH: 3l2fo77zfjz3gwbd5olpxcwrgynxfhyk, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
libpng 1.6.34 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib 1.2.11 gcc@5.5.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04_noentry
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: zlib 1.2.11
      gcc@5.5.0 linux-ubuntu18.04-x86_64, HASH: 3l2fo77zfjz3gwbd5olpxcwrgynxfhyk,
    MIRROR_URL: 'https://mirror.spack.io'}
ncurses 6.1 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 gcc@5.5.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7_noentry
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      gcc@5.5.0 linux-centos7-x86_64, HASH: urtbfu4skrswjibs7g5r2cfscvh6ntvk, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
ncurses 6.1 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 gcc@5.5.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04_noentry
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      gcc@5.5.0 linux-ubuntu18.04-x86_64, HASH: urtbfu4skrswjibs7g5r2cfscvh6ntvk,
    MIRROR_URL: 'https://mirror.spack.io'}
pkgconf 1.4.2 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_centos_7_noentry
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: ajmd4zrwcwwmkpmkmannbwg3v3lia5m7,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
pkgconf 1.4.2 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_ubuntu_18.04_noentry
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: ajmd4zrwcwwmkpmkmannbwg3v3lia5m7,
    MIRROR_URL: 'https://mirror.spack.io'}
readline 7.0 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 gcc@5.5.0 linux-centos7-x86_64, ncurses 6.1 gcc@5.5.0
      linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7_noentry
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      gcc@5.5.0 linux-centos7-x86_64;ncurses 6.1 gcc@5.5.0 linux-centos7-x86_64, HASH: 7ghip7owubroxsvey3fsjbrslcyrufkr,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
readline 7.0 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 gcc@5.5.0 linux-ubuntu18.04-x86_64, ncurses 6.1 gcc@5.5.0
      linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04_noentry
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      gcc@5.5.0 linux-ubuntu18.04-x86_64;ncurses 6.1 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    HASH: 7ghip7owubroxsvey3fsjbrslcyrufkr, MIRROR_URL: 'https://mirror.spack.io'}
rebuild-index:
  image: scottwittenburg/spack_builder_centos_7_noentry
  script: ./rebuild-index.sh
  stage: stage-rebuild-index
  tags: [spack-k8s]
  variables: {MIRROR_URL: 'https://mirror.spack.io'}
stages: [stage-0, stage-1, stage-2, stage-rebuild-index]
zlib 1.2.11 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_centos_7_noentry
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: omy635k24jq6hpqhkfvnqykyee6qami2,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
zlib 1.2.11 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_ubuntu_18.04_noentry
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: omy635k24jq6hpqhkfvnqykyee6qami2,
    MIRROR_URL: 'https://mirror.spack.io'}
