libpng 1.6.34 clang@7.0.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib 1.2.11 clang@7.0.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: zlib 1.2.11
      clang@7.0.0 linux-centos7-x86_64, HASH: jld6sgljd6s2px6pq3p7fd7vk2w5rx7s, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
libpng 1.6.34 clang@7.0.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib 1.2.11 clang@7.0.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: zlib 1.2.11
      clang@7.0.0 linux-ubuntu18.04-x86_64, HASH: jld6sgljd6s2px6pq3p7fd7vk2w5rx7s,
    MIRROR_URL: 'https://mirror.spack.io'}
libpng 1.6.34 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib 1.2.11 gcc@5.5.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: zlib 1.2.11
      gcc@5.5.0 linux-centos7-x86_64, HASH: 2vicq3d4jut2e773agkit5mxhbgjjb4a, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
libpng 1.6.34 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib 1.2.11 gcc@5.5.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: zlib 1.2.11
      gcc@5.5.0 linux-ubuntu18.04-x86_64, HASH: 2vicq3d4jut2e773agkit5mxhbgjjb4a,
    MIRROR_URL: 'https://mirror.spack.io'}
ncurses 6.1 clang@7.0.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 clang@7.0.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      clang@7.0.0 linux-centos7-x86_64, HASH: y5zlifztfelfaad6r67ayiwbjir3v2ew, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
ncurses 6.1 clang@7.0.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 clang@7.0.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      clang@7.0.0 linux-ubuntu18.04-x86_64, HASH: y5zlifztfelfaad6r67ayiwbjir3v2ew,
    MIRROR_URL: 'https://mirror.spack.io'}
ncurses 6.1 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 gcc@5.5.0 linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      gcc@5.5.0 linux-centos7-x86_64, HASH: qkjccof3uvo5gyq6n7apkklvne2sp6eg, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
ncurses 6.1 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 gcc@5.5.0 linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      gcc@5.5.0 linux-ubuntu18.04-x86_64, HASH: qkjccof3uvo5gyq6n7apkklvne2sp6eg,
    MIRROR_URL: 'https://mirror.spack.io'}
pkgconf 1.4.2 clang@7.0.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: jezldjw3s3wsk5y37thyqqmr5sv6hf33,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
pkgconf 1.4.2 clang@7.0.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: jezldjw3s3wsk5y37thyqqmr5sv6hf33,
    MIRROR_URL: 'https://mirror.spack.io'}
pkgconf 1.4.2 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: bp4fmnslswquzifwktrisayzxpyjsweo,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
pkgconf 1.4.2 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: bp4fmnslswquzifwktrisayzxpyjsweo,
    MIRROR_URL: 'https://mirror.spack.io'}
readline 7.0 clang@7.0.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 clang@7.0.0 linux-centos7-x86_64, ncurses 6.1 clang@7.0.0
      linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      clang@7.0.0 linux-centos7-x86_64;ncurses 6.1 clang@7.0.0 linux-centos7-x86_64,
    HASH: afai3qx737g37mx62w5u2qh2cougwqfc, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
readline 7.0 clang@7.0.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf 1.4.2 clang@7.0.0 linux-ubuntu18.04-x86_64, ncurses 6.1 clang@7.0.0
      linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: pkgconf 1.4.2
      clang@7.0.0 linux-ubuntu18.04-x86_64;ncurses 6.1 clang@7.0.0 linux-ubuntu18.04-x86_64,
    HASH: afai3qx737g37mx62w5u2qh2cougwqfc, MIRROR_URL: 'https://mirror.spack.io'}
readline 7.0 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [ncurses 6.1 gcc@5.5.0 linux-centos7-x86_64, pkgconf 1.4.2 gcc@5.5.0
      linux-centos7-x86_64]
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: ncurses 6.1
      gcc@5.5.0 linux-centos7-x86_64;pkgconf 1.4.2 gcc@5.5.0 linux-centos7-x86_64,
    HASH: vuigreezu2lulh3car2jdmuvwsfokeqx, MIRROR_URL: 'https://mirror.spack.io',
    SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
readline 7.0 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [ncurses 6.1 gcc@5.5.0 linux-ubuntu18.04-x86_64, pkgconf 1.4.2 gcc@5.5.0
      linux-ubuntu18.04-x86_64]
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: ncurses 6.1
      gcc@5.5.0 linux-ubuntu18.04-x86_64;pkgconf 1.4.2 gcc@5.5.0 linux-ubuntu18.04-x86_64,
    HASH: vuigreezu2lulh3car2jdmuvwsfokeqx, MIRROR_URL: 'https://mirror.spack.io'}
rebuild-index:
  image: scottwittenburg/spack_builder_centos_7
  script: ./rebuild-index.sh
  stage: stage-rebuild-index
  tags: [spack-k8s]
  variables: {MIRROR_URL: 'https://mirror.spack.io'}
stages: [stage-0, stage-1, stage-2, stage-rebuild-index]
zlib 1.2.11 clang@7.0.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: mivoflmfkni3ejofqq22rrdt3g6ovnnv,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
zlib 1.2.11 clang@7.0.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: mivoflmfkni3ejofqq22rrdt3g6ovnnv,
    MIRROR_URL: 'https://mirror.spack.io'}
zlib 1.2.11 gcc@5.5.0 linux-centos7-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_centos_7
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: ymics2ib4ovm63pwnahmf6morsi7olq6,
    MIRROR_URL: 'https://mirror.spack.io', SPACK_FIND_COMPILER_PATHS: /opt/gcc/gcc-5.5.0}
zlib 1.2.11 gcc@5.5.0 linux-ubuntu18.04-x86_64:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/spack_builder_ubuntu_18.04
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [spack-k8s]
  variables: {CDASH_BASE_URL: 'https://cdash.spack.io', DEPENDENCIES: '', HASH: ymics2ib4ovm63pwnahmf6morsi7olq6,
    MIRROR_URL: 'https://mirror.spack.io'}
