libpng@1.6.34%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /a5oblht:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [zlib@1.2.11%gcc@5.4.0+optimize+pic+shared arch=linux-ubuntu16.04-x86_64
      /5nus6kn]
  image: scottwittenburg/binary_check_runner
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [my-tag]
  variables: {HASH: a5oblht5r7sql6oimuiq3cn2w4kaikqp, MIRROR_URL: 'http://172.17.0.1:8081/',
    SHORT_SPEC: libpng@1.6.34%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /a5oblht, SPEC_NAME: libpng@1.6.34%gcc@5.4.0
      arch=linux-ubuntu16.04-x86_64}
ncurses@6.1%gcc@5.4.0~symlinks~termlib arch=linux-ubuntu16.04-x86_64 /3o765ou:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [pkgconf@1.4.2%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /fovrh7a]
  image: scottwittenburg/binary_check_runner
  script: [./rebuild-package.sh]
  stage: stage-1
  tags: [my-tag]
  variables: {HASH: 3o765ourmesfrji6yeclb4wb5w54aqbh, MIRROR_URL: 'http://172.17.0.1:8081/',
    SHORT_SPEC: ncurses@6.1%gcc@5.4.0~symlinks~termlib arch=linux-ubuntu16.04-x86_64
      /3o765ou, SPEC_NAME: ncurses@6.1%gcc@5.4.0~symlinks~termlib arch=linux-ubuntu16.04-x86_64}
pkgconf@1.4.2%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /fovrh7a:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/binary_check_runner
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [my-tag]
  variables: {HASH: fovrh7alpft646n6mhis5mml6k6e5f4v, MIRROR_URL: 'http://172.17.0.1:8081/',
    SHORT_SPEC: pkgconf@1.4.2%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /fovrh7a, SPEC_NAME: pkgconf@1.4.2%gcc@5.4.0
      arch=linux-ubuntu16.04-x86_64}
readline@7.0%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /nxhwrg7:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: [ncurses@6.1%gcc@5.4.0~symlinks~termlib arch=linux-ubuntu16.04-x86_64
      /3o765ou, pkgconf@1.4.2%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /fovrh7a]
  image: scottwittenburg/binary_check_runner
  script: [./rebuild-package.sh]
  stage: stage-2
  tags: [my-tag]
  variables: {HASH: nxhwrg7xwc6nbsm2v4ezwe63l6nfidbi, MIRROR_URL: 'http://172.17.0.1:8081/',
    SHORT_SPEC: readline@7.0%gcc@5.4.0 arch=linux-ubuntu16.04-x86_64 /nxhwrg7, SPEC_NAME: readline@7.0%gcc@5.4.0
      arch=linux-ubuntu16.04-x86_64}
stages: [stage-0, stage-1, stage-2]
zlib@1.2.11%gcc@5.4.0+optimize+pic+shared arch=linux-ubuntu16.04-x86_64 /5nus6kn:
  artifacts:
    paths: [local_mirror/build_cache]
  dependencies: []
  image: scottwittenburg/binary_check_runner
  script: [./rebuild-package.sh]
  stage: stage-0
  tags: [my-tag]
  variables: {HASH: 5nus6knzumx4ik2yl44jxtgtsl7d54xb, MIRROR_URL: 'http://172.17.0.1:8081/',
    SHORT_SPEC: zlib@1.2.11%gcc@5.4.0+optimize+pic+shared arch=linux-ubuntu16.04-x86_64
      /5nus6kn, SPEC_NAME: zlib@1.2.11%gcc@5.4.0+optimize+pic+shared arch=linux-ubuntu16.04-x86_64}
