#=============================================================================
# Project settings
#=============================================================================
# Only build master and develop on push; do not build every branch.
branches:
  only:
    - master
    - develop
    - /^releases\/.*$/

#=============================================================================
# Build matrix
#=============================================================================

dist: xenial

jobs:
  fast_finish: true
  include:
    - stage: 'style checks'
      python: '2.7'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=flake8
    - stage: 'unit tests + documentation'
      python: '2.6'
      dist: trusty
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '2.7'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '3.4'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '3.5'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '3.6'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '3.7'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '3.6'
      sudo: required
      os: linux
      language: python
      env: TEST_SUITE=doc
    - os: osx
      language: generic
      env: [ TEST_SUITE=unit, PYTHON_VERSION=2.7 ]
# mpich (AutotoolsPackage)
    - stage: 'build tests'
      python: '2.7'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=mpich' ]
# astyle (MakefilePackage)
    - python: '2.7'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=astyle' ]
# tut (WafPackage)
    - python: '2.7'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=tut' ]
# py-setuptools (PythonPackage)
    - python: '2.7'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=py-setuptools' ]
# perl-dbi (PerlPackage)
#    - python: '2.7'
#      os: linux
#      language: python
#      env: [ TEST_SUITE=build, 'SPEC=perl-dbi' ]
# openjpeg (CMakePackage + external cmake)
    - python: '2.7'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=openjpeg' ]
# r-rcpp (RPackage + external R)
    - python: '2.7'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=r-rcpp' ]
# mpich (AutotoolsPackage)
    - python: '3.6'
      os: linux
      language: python
      env: [ TEST_SUITE=build, 'SPEC=mpich' ]
    - stage: 'docker build'
      sudo: required
      os: linux
      language: generic
      env: TEST_SUITE=docker
  allow_failures:
    - env: TEST_SUITE=docker

stages:
  - 'style checks'
  - 'unit tests + documentation'
  - 'build tests'
  - name: 'docker build'
    if: type = push AND branch IN (develop, master)


#=============================================================================
# Environment
#=============================================================================
# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false

# Docs need graphviz to build
addons:
  apt:
    packages:
      - ccache
      - gfortran
      - mercurial
      - graphviz
      - gnupg2
      - cmake
      - ninja-build
      - r-base
      - r-base-core
      - r-base-dev
      - perl
      - perl-base

# ~/.ccache needs to be cached directly as Travis is not taking care of it
# (possibly because we use 'language: python' and not 'language: c')
cache:
  pip: true
  ccache: true
  directories:
    - ~/.mirror
    - ~/.ccache

# Work around Travis's lack of support for Python on OSX
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        export HOMEBREW_NO_AUTO_UPDATE=1;
        rm /usr/local/include/c++ ;
        brew ls --versions python@2 > /dev/null || brew install python@2;
        brew ls --versions gcc      > /dev/null || brew install gcc;
        brew ls --versions gnupg2   > /dev/null || brew install gnupg2;
        brew ls --versions ccache   > /dev/null || brew install ccache;
        pip2 install --upgrade pip;
        pip2 install virtualenv;
        virtualenv venv;
        source venv/bin/activate;
    fi
  - ccache -M 2G && ccache -z

# Install various dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade six
  - pip install --upgrade setuptools
  - pip install --upgrade codecov
  - pip install --upgrade flake8
  - pip install --upgrade pep8-naming
  - if [[ "$TEST_SUITE" == "doc" ]]; then
        pip install --upgrade -r lib/spack/docs/requirements.txt;
    fi

before_script:
  # Need this for the git tests to succeed.
  - git config --global user.email "spack@example.com"
  - git config --global user.name "Test User"

  # Need this to be able to compute the list of changed files
  - git fetch origin develop:develop

  # Set up external deps for build tests, b/c they take too long to compile
  - if [[ "$TEST_SUITE" == "build" ]]; then
        cp share/spack/qa/configuration/*.yaml etc/spack/;
    fi

#=============================================================================
# Building
#=============================================================================
services:
  - docker

script:
  - share/spack/qa/run-$TEST_SUITE-tests
  - if [[ "$TEST_SUITE" == "docker build" ]]; then
        login_attempted=0; login_success=0;
        for config in share/spack/docker/config/* ; do
            source "$config" ;
            ./share/spack/docker/build-image.sh;
            if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
                if [ "$login_attempted" '=' '0' ]; then
                    if echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; then
                        login_success=1;
                    fi;
                    login_attempted=1;
                fi;
                if [ "$login_success" '=' '1' ]; then
                    ./share/spack/docker/push-image.sh;
                fi
            fi
        done;
    fi
  - if [[ "$TEST_SUITE" == "unit" || "$TEST_SUITE" == "build" ]]; then
        codecov --env PYTHON_VERSION
                --required --flags "${TEST_SUITE}${TRAVIS_OS_NAME}";
    fi

after_success:
  - ccache -s

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    recipients: tgamblin@llnl.gov
    on_success: change
    on_failure: always
