language: python

# Construct build matrix
python:
  - 2.6
  - 2.7

env:
  - TEST_SUITE=unit
  - TEST_SUITE=flake8
  - TEST_SUITE=doc

matrix:
  exclude:
  - python: 2.6
    # Flake8 no longer supports Python 2.6
    env: TEST_SUITE=flake8

# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false

# Docs need graphviz to build
addons:
  apt:
    packages:
      - graphviz

# Install various dependencies
install:
  - pip install coveralls
  - pip install flake8
  - pip install sphinx
  - pip install mercurial

before_script:
  # Need this for the git tests to succeed.
  - git config --global user.email "spack@example.com"
  - git config --global user.name "Test User"

  # Need this to be able to compute the list of changed files
  - git fetch origin develop:develop

script: share/spack/qa/run-$TEST_SUITE-tests

after_success:
  - if [[ $TEST_SUITE == unit && $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi

notifications:
  email:
    recipients: tgamblin@llnl.gov
    on_success: change
    on_failure: always
