#=============================================================================
# Project settings
#=============================================================================
# Only build master and develop on push; do not build every branch.
branches:
  only:
    - master
    - develop
    - /^releases\/.*$/

#=============================================================================
# Build matrix
#=============================================================================
matrix:
  include:
    - python: '2.6'
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '2.7'
      os: linux
      language: python
      env: TEST_SUITE=unit
    - python: '2.7'
      os: linux
      language: python
      env: TEST_SUITE=flake8
    - python: '2.7'
      os: linux
      language: python
      env: TEST_SUITE=doc
    - os: osx
      language: generic
      env: [ TEST_SUITE=unit, PYTHON_VERSION=2.7 ]

#=============================================================================
# Environment
#=============================================================================
# Use new Travis infrastructure (Docker can't sudo yet)
sudo: false

# Docs need graphviz to build
addons:
  apt:
    packages:
      - gfortran
      - graphviz
      - libyaml-dev

# Work around Travis's lack of support for Python on OSX
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions python > /dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gcc    > /dev/null || brew install gcc;    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

# Install various dependencies
install:
  - pip install --upgrade codecov
  - pip install --upgrade flake8
  - pip install --upgrade sphinx
  - pip install --upgrade mercurial

before_script:
  # Need this for the git tests to succeed.
  - git config --global user.email "spack@example.com"
  - git config --global user.name "Test User"

  # Need this to be able to compute the list of changed files
  - git fetch origin develop:develop

#=============================================================================
# Building
#=============================================================================
script: share/spack/qa/run-$TEST_SUITE-tests

after_success:
  - if [[ $TEST_SUITE == unit && $TRAVIS_PYTHON_VERSION == 2.7 && $TRAVIS_OS_NAME == "linux" ]]; then codecov --env PY_VERSION; fi

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    recipients: tgamblin@llnl.gov
    on_success: change
    on_failure: always
