packages:
  # SLES DEFAULTS
  all:
    providers:
      blas: [cray-libsci]
      lapack: [cray-libsci]
      mpi: [cray-mpich]
      tbb: [intel-tbb]
      scalapack: [netlib-scalapack]
    target:: [zen4]
    variants: +mpi

  # VARIANT PREFERENCES/REQUIREMENTS
  binutils:
    variants: +ld +gold +headers +libiberty ~nls
  hdf5:
    variants: +fortran +hl +shared
  libunwind:
    variants: +pic +xz
  ncurses:
    require: "@6.3 +termlib"
  openblas:
    require: "@0.3.20"
    variants: threads=openmp
  xz:
    variants: +pic
  elfutils:
    variants: +bzip2 ~nls +xz
    require: "%gcc"
  unzip:
    require: "%gcc"

  # EXTERNALS
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.25 %cce
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/cray/10.0/
      modules:
      - cray-mpich/8.1.25
    - spec: cray-mpich@8.1.25 %dpcpp
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/intel/19.0/
      modules:
      - cray-mpich/8.1.25
    - spec: cray-mpich@8.1.25 %gcc
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/gnu/9.1/
      modules:
      - cray-mpich/8.1.25
    - spec: cray-mpich@8.1.25 %intel
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/intel/19.0/
      modules:
      - cray-mpich/8.1.25
    - spec: cray-mpich@8.1.25 %nvhpc
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/nvidia/20.7/
      modules:
      - cray-mpich/8.1.25
    - spec: cray-mpich@8.1.25 %oneapi
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/intel/19.0/
      modules:
      - cray-mpich/8.1.25
    - spec: cray-mpich@8.1.25 %rocmcc
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/amd/5.0/
      modules:
      - cray-mpich/8.1.25
  cray-libsci:
    buildable: false
    externals:
    - spec: cray-libsci@23.02.1.1 %cce
      prefix: /opt/cray/pe/libsci/23.02.1.1/CRAY/9.0/x86_64/
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.02.1.1 %dpcpp
      prefix: /opt/cray/pe/libsci/23.02.1.1/INTEL/2022.2/x86_64/
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.02.1.1 %gcc
      prefix: /opt/cray/pe/libsci/23.02.1.1/GNU/9.1/x86_64/
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.02.1.1 %intel
      prefix: /opt/cray/pe/libsci/23.02.1.1/INTEL/2022.2/x86_64/
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.02.1.1 %nvhpc
      prefix: /opt/cray/pe/libsci/23.02.1.1/NVIDIA/20.7/x86_64/
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.02.1.1 %oneapi
      prefix: /opt/cray/pe/libsci/23.02.1.1/INTEL/2022.2/x86_64/
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.02.1.1 %rocmcc
      prefix: /opt/cray/pe/libsci/23.02.1.1/AMD/4.0/x86_64/
      modules:
      - cray-libsci/23.02.1.1
