modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - archngv
      - asciitoh5
      - brainbuilder
      - brayns
      - brayns-brainatlas
      - brayns-topologyviewer
      - brion+python
      - circuit-build
      - circuit-analysis
      - connectome-tools
      - emsim
      - functionalizer
      - meshball
      - model-neocortex
      - nest
      - neurodamus-core
      - neurodamus-hippocampus
      - neurodamus-neocortex
      - neurodamus-thalamus
      - neurodamus-mousify
      - parquet-converters
      - placement-algorithm
      - psp-validation
      - py-basalt
      - py-bbp-analysis-framework
      - py-bglibpy
      - py-bluepy
      - py-bluepyefe
      - py-bluepymm
      - py-bluepyopt
      - py-bluepysnap
      - py-currentscape
      - py-efel
      - py-entity-management
      - py-jupyter-notebook
      - py-minis-validation
      - py-morph-tool
      - py-morphio
      - py-morphology-repair-workflow
      - 'py-mvdtool%gcc'
      - py-neurodamus
      - py-simwriter
      - py-sonata-network-reduction
      - py-pytouchreader
      - regiodesics
      - reportinglib
      - spatial-index
      - spykfunc
      - 'synapsetool%gcc'
      - steps
      - touchdetector
      - ultraliser
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    all:
      autoload: 'all'
      suffixes:
        '^coreneuron+knl': 'knl'
        '+common': 'commonmods'  # neurodamus-core
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
