config:
  db_lock_timeout: 120
  shared_linking:
    missing_library_policy: warn
  install_tree:
    root: /home/software/spack
    padded_length: 256
    projections:
      all: '{architecture}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
  build_stage:
  - $spack/tmp/stage

