packages: {}

# CI should never build develop/main/master versions of packages. Current issues:
# - e4s/dav
#   - hdf5-vol-async => argobot@main
# - aws-isc-aarch64
#   - sse2neon

# packages:
#   all:
#     require: "@:999999999"