compilers:
- compiler:
    spec: cce@=18.0.0
    paths:
      cc: /opt/cray/pe/cce/18.0.0/bin/craycc
      cxx: /opt/cray/pe/cce/18.0.0/bin/crayCC
      f77: /opt/cray/pe/cce/18.0.0/bin/crayftn
      fc: /opt/cray/pe/cce/18.0.0/bin/crayftn
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=8.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []