---
name: Codespell

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - name: Codespell
        uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
