name: maintainers

on:
  pull_request:
    branches:
    - develop
    paths:
      - 'var/spack/repos/builtin/packages/**'
    types:
      - opened

jobs:
  maintainers:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Spack
      uses: actions/checkout@v2
    - name: Get Changed Files
      id: changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ','
    - name: Get Maintainers
      id: maintainers
      uses: ./.github/actions/maintainers
      with:
        author: ${{ github.event.pull_request.user.login }}
        changes: ${{ steps.changes.outputs.files }}
    - name: Notify Maintainers
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          @${{ steps.maintainers.outputs.maintainers }} can you review this PR?

          This PR modifies the following package(s), for which you are listed as a maintainer:

          * ${{ steps.maintainers.outputs.packages-with-maintainers }}
      if: ${{ steps.maintainers.outputs.maintainers }}
    - name: Request Maintainers
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Hi @${{ github.event.pull_request.user.login }}! I noticed that the following package(s) don't yet have maintainers:

          * ${{ steps.maintainers.outputs.packages-without-maintainers }}

          Are you interested in adopting these package(s)? If so, simply add the following to the package class:
          ```python
              maintainers = ['${{ github.event.pull_request.user.login }}']
          ```
          You don't have to be a Spack expert or package developer in order to be a "maintainer", it just gives us a list of users willing to review PRs or debug issues relating to this package.
      if: ${{ steps.maintainers.outputs.packages-without-maintainers }}
